### ISSUE TITLE
Evaluation Results.

### ISSUE THREAD

**Issue by xj-martin** [JaminJeong/SC_U-NET#1]
Hi, I have already trained the model you provided, but I can't find where to get the evaluation results. Thank you very much for your help.

**Comment by JaminJeong** [comment]
this model generate images  that is made by sound. generative model don't have evaluation results. It just have L2 loss. if L2 loss is small, the model generate images similar to the original.

**Comment by xj-martin** [comment]
Actually，I want to know how you get the SDR.Thanks for your help.
